"use strict";
exports.__esModule = true;
var classMovie_1 = require("./classMovie");
var classProfessional_1 = require("./classProfessional");
var person1 = new classProfessional_1.Professional("John Soplapo", 69, "Male", 87, 1.85, "Blonde", "Blue", "Mongoloid", true, "Australian", 5, "Actor");
var person2 = new classProfessional_1.Professional("Vladimir Putin", 53, "Male", 90, 1.92, "Bald", "Green", "Caucasian", false, "Russian", 0, "Director");
var person3 = new classProfessional_1.Professional("Andrea Mostacho", 34, "Female", 61, 1.69, "Black", "Blue", "Caucasian", false, "Italian", 2, "Actor");
var person4 = new classProfessional_1.Professional("Miguel Lacambra", 30, "Male", 80, 1.70, "Black", "Black", "Caucasian", false, "Spanish", 1, "Actor");
var person5 = new classProfessional_1.Professional("Angel Demon", 48, "Male", 120, 1.60, "Bald", "Blue", "Black", true, "EEUU", 3, "Writer");
var movie1 = new classMovie_1.Movie("Ovejas asesinas", 2002, "Spain", "Terror");
movie1.actors = [person1, person3, person4];
movie1.director = "Andres Cabreado";
movie1.writer = "Armando Armado";
movie1.language = "Spanish";
movie1.plataform = "Netflix";
movie1.isMCU = true;
movie1.mainCharacterName = "Martin Cabrales";
movie1.producer = "Jordi ENP";
movie1.distributor = "Mis Cojo...";
var movie2 = new classMovie_1.Movie("Niggas in da house", 2012, "EEUU", "Comedy");
movie2.actors = [person1, person3, person4];
movie2.director = "Hitler";
movie2.writer = "Franco";
movie2.language = "English";
movie2.plataform = "Prime-video";
movie2.isMCU = false;
movie2.mainCharacterName = "Erik Dick Head";
movie2.producer = "Eminem";
movie2.distributor = "KAMEHAMEHA";
var movie3 = new classMovie_1.Movie("El despierto no está dormido", 1995, "Spain", "Drama");
movie3.actors = [person1, person3, person4];
movie3.director = "Vlad Tepes";
movie3.writer = "Belen Esteban";
movie3.language = "Spanish";
movie3.plataform = "X-Video";
movie3.isMCU = true;
movie3.mainCharacterName = "Jordi ENP";
movie3.producer = "La Duquesa de Alba";
movie3.distributor = "Foro Coches";
console.log(movie1.toString());
console.log(movie2.toString());
console.log(movie3.toString());
var movies = [movie1, movie2, movie3];
console.log(movies.toString());
